// pages/index.tsx

import Head from "next/head";
import CustomerRegistration from "./customerRegistration";
import Transaction from "./transaction";

const HomePage: React.FC= () => (
  <>
      {/* Head Section */}
      <Head>
          <title>PT ABC Integration UI</title>
          <meta name='description' content='Generated by create next app'/>
      </Head>

      {/* Main Content */}
      {/* Pilih salah satu untuk ditampilkan */}
      {/* Uncomment salah satu dari dua bagian di bawah sesuai kebutuhan */}

      {/* Bagian Registrasi Customer */}
      <CustomerRegistration />

      {/* Bagian Transaksi */}
       {/* <Transaction /> */}
      
   </>
);

export default HomePage;
